# Generated by Selenium IDE
import pytest # Framework de Teste de Unidade
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSelecionarProduto():
  def setup_method(self, method):
      options = Options()
      options.add_argument("--incognito")
      self.driver = webdriver.Chrome()
      self.vars = {}
      self.driver.implicitly_wait(5) # irá esperar qualquer elemento por até 5 segundos <-- Melhor
  
  def teardown_method(self, method):
    self.driver.quit()
    
  